#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: ibm-semeru-runtimes:open-21-jdk

definitions:
  caches:
    # Bitbucket doesn't supply a default cache for the Gradle wrapper
    # The cache is invalidated when the gradle-wrapper.properties change
    gradle-wrapper:
      key:
        files:
          - gradle/wrapper/gradle-wrapper.properties
      path: ~/.gradle/wrapper

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - gradle
            - gradle-wrapper
          script:
            - ./gradlew build test
          after-script:
            - pipe: atlassian/checkstyle-report:0.5.4
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:3.2.0
